### ISSUE TITLE
[BUG] Missing ip_address parameter in profile raises error but LXC container is created anyway

### ISSUE THREAD

**Issue by I3urny** [salt-extensions/saltext-proxmox#21]
**Description**
If a profile is used without specifying the `ip_address` parameter an error with the message "Could not determine an IP address to use" is raised but the LXC container is created anyway.

**Setup**
N/A

**Steps to Reproduce the behavior**
Using the following configs with `salt-cloud`:

cloud.profiles.d/ubuntu.conf:
```yaml
lxc-profile:
    provider: proxmox-lab
    technology: lxc
    host: proxmox

    image: local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst
    password: topsecret
    net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.101.1,ip=192.168.101.21/24,tag=101,type=veth
```

Start command with: `salt-cloud -p lxc-profile test-ct`

The first run will result in the following error message:
```
$ salt-cloud -p lxc-profile test-ct
Usage: salt-cloud [options] <-m MAP | -p PROFILE> <NAME> [NAME2 ...]

salt-cloud: error: There was a profile error: Could not determine an IP address to use
```

A repeated run - regardless if the configuration is fixed or not - will produce:
```
$ salt-cloud -p lxc-profile test-ct
[ERROR   ] test-ct already exists under proxmox-lab:proxmox
test-ct:
    ----------
    Error:
        test-ct already exists under proxmox-lab:proxmox
```

**Expected behavior**
IMO, the VM should not exist if an error occurs during the `create()` function.
Subsequent calls with a corrected profile shouldn't end prematurely because an incomplete/incorrect VM took its place.

**Screenshots**
N/A

**Versions Report**
N/A

**Additional context**
This is closely related to this comment https://github.com/saltstack/salt/issues/56633#issuecomment-708278555.
The code uses an undocumented parameter called `agent_get_ip` to determine the way the IP address used to connect to the VM is set. 

https://github.com/salt-extensions/saltext-proxmox/blob/3a12d1227d48402b94408b2955e029b9579028ef/src/saltext/proxmox/clouds/proxmox.py#L719-L730

There currently is no option if `net0` was used instead of `ip_address` so you have to define `ip_address` even though the information is already included in the former parameter.

For QEMU there seems to be a different version to get the IP address which also destroys the VM if a connection cannot be established:
https://github.com/salt-extensions/saltext-proxmox/blob/3a12d1227d48402b94408b2955e029b9579028ef/src/saltext/proxmox/clouds/proxmox.py#L751-L763
