### ISSUE TITLE
[BUG] cannot use parameters with index over 9

### ISSUE THREAD

**Issue by I3urny** [salt-extensions/saltext-proxmox#29]
**Description**
Using parameters with an index bigger than 9 will be quietly discarded by the cloud module.

This problem is caused by this code: https://github.com/salt-extensions/saltext-proxmox/blob/3a12d1227d48402b94408b2955e029b9579028ef/src/saltext/proxmox/clouds/proxmox.py#L918-L926

With the `net[n]` parameter for example, this limits a profile to use: "net0" to "net9"

**Setup**
N/A

**Steps to Reproduce the behavior**
cloud.profiles.d/ubuntu.conf:
```yaml
test-ct:
    provider: my-proxmox-config
    technology: lxc
    host: proxmox

    image: local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst
    password: topsecret
    net10: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.101.1,ip=192.168.101.22/24,tag=101,type=veth
```

**Expected behavior**
LXC CT should be created with net10 being set.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
Salt Version:
            Salt: 3006.3

Python Version:
          Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
            cffi: 1.14.6
        cherrypy: unknown
        dateutil: 2.8.1
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
          Jinja2: 3.1.2
         libgit2: Not Installed
    looseversion: 1.0.2
        M2Crypto: Not Installed
            Mako: Not Installed
         msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       packaging: 22.0
       pycparser: 2.21
        pycrypto: Not Installed
    pycryptodome: 3.9.8
          pygit2: Not Installed
    python-gnupg: 0.4.8
          PyYAML: 6.0.1
           PyZMQ: 23.2.0
          relenv: 0.13.10
           smmap: Not Installed
         timelib: 0.2.4
         Tornado: 4.5.3
             ZMQ: 4.3.4

Salt Extensions:
 saltext.proxmox: 1.0.0

System Versions:
            dist: ubuntu 22.04.2 jammy
          locale: utf-8
         machine: x86_64
         release: 5.15.0-82-generic
          system: Linux
         version: Ubuntu 22.04.2 jammy
</summary>
</details>

**Additional context**
We can keep the arbitrary limit instead of enabling up to N.
However, this limit must be documented and it would be nice if the user received a warning like described in https://github.com/salt-extensions/saltext-proxmox/issues/8#issuecomment-1727073103
