### ISSUE TITLE
salt-pip installs incorrect version of saltext-proxmox

### ISSUE THREAD

**Issue by BadgerOps** [salt-extensions/saltext-proxmox#36]
**Description**

 Hello all,

I'm attempting to use this extension, on a (physical) AlmaLinux 8.9 host, targeting a physically separate proxmox cluster.

It _appears_ that the version of `saltext-proxmox` that is being downloaded is the soon-to-be-deprecated version as seen below from the whl that is downloaded from pypi:

```
"""
Proxmox Cloud Module
======================

.. versionadded:: 2014.7.0

.. versionchanged:: 3006.0

The Proxmox cloud module is used to control access to cloud providers using
the Proxmox system (KVM / LXC).

Set up the cloud configuration at ``/etc/salt/cloud.providers`` or
 ``/etc/salt/cloud.providers.d/proxmox.conf``:

.. code-block:: yaml

    my-proxmox-config:
      # Proxmox account information
      user: myuser@pam or myuser@pve
      password: mypassword
      url: hypervisor.domain.tld
      port: 8006
      driver: proxmox
      verify_ssl: True

:maintainer: Frank Klaassen <frank@cloudright.nl>
:depends: requests >= 2.2.1
"""
```

This is on a fresh salt 3007 deploy, the only extra module deployed is this one, via `salt-pip install saltext-proxmox` 

```bash
salt-pip install saltext-proxmox --verbose                                                                                                                                                           
Using pip 24.0 from /opt/saltstack/salt/lib/python3.10/site-packages/pip (python 3.10)
Collecting saltext-proxmox
  Obtaining dependency information for saltext-proxmox from https://files.pythonhosted.org/packages/33/8b/15ea94dcde9cd7093f255de5834b915ebb86b8cc25e87e9896a1b99cfb37/saltext.proxmox-1.1.0-py2.py3-none-any.whl.metadata
  Using cached saltext.proxmox-1.1.0-py2.py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: requests>=2.2.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from saltext-proxmox) (2.31.0)                                                                                    
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.2.1->saltext-proxmox) (3.2.0)                                                           
Requirement already satisfied: idna<4,>=2.5 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.2.1->saltext-proxmox) (3.4)                                                                         
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.2.1->saltext-proxmox) (1.26.18)                                                               
Requirement already satisfied: certifi>=2017.4.17 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.2.1->saltext-proxmox) (2023.7.22)                                                             
Using cached saltext.proxmox-1.1.0-py2.py3-none-any.whl (19 kB)
Installing collected packages: saltext-proxmox
Successfully installed saltext-proxmox-1.1.0
```

The exact URL that is pulled on my system is:

> https://files.pythonhosted.org/packages/33/8b/15ea94dcde9cd7093f255de5834b915ebb86b8cc25e87e9896a1b99cfb37/saltext.proxmox-1.1.0-py2.py3-none-any.whl.metadata

It _does_ appear that the version visible at https://pypi.org/project/saltext.proxmox/#files corresponds with the latest release on this project, so I'm a little confused how this is happening - I'm guessing maybe it is related to how pypi is handling the re-use of the same package name?

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Logs shown above

**Expected behavior**

Successful install and usage of this salt-extension

**Screenshots**

**Versions Report**

```yaml
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: almalinux 8.9 Midnight Oncilla
        locale: utf-8
       machine: x86_64
       release: 4.18.0-513.18.1.el8_9.x86_64
        system: Linux
       version: AlmaLinux 8.9 Midnight Oncilla
```

I'm following along with the instructions in this repo after building & serving them.

I figured I'd submit this issue in case someone else is having the same issue, or maybe I'm just _really bad_ at `pip` 

Cheers,

-BadgerOps
