### ISSUE TITLE
[BUG] There was a profile error: name '__opts__' is not defined / in filter_event (salt/utils/cloud.py)

### ISSUE THREAD

**Issue by NMi-ru** [salt-extensions/saltext-proxmox#45]
**Description**
// I am not sure if this is a bug in the saltext.proxmox or in the salt-cloud

I am getting an error while trying to create an LXC container:
salt-cloud --no-deploy --profile my-first-cloud-profile my-test-hostname
[ERROR   ] There was a profile error: name '__opts__' is not defined

**Setup**
/etc/salt/cloud.providers.d/test-cloud-provider-proxmox.conf:
```
my-first-cloud-provider-proxmox:
  user: root@pam
  token: saltstack=long-token-here
  url: https://proxmox-hostname-here:8006
  driver: proxmox
```

/etc/salt/cloud.profiles.d/my-test-cloud-profile.conf:
```
my-first-cloud-profile:
  provider: my-first-cloud-provider-proxmox
  technology: lxc
  name: my-test-name

  create:
    vmid: 1000
    ostemplate: local:vztmpl/centos-9-stream-default_20240828_amd64.tar.xz
    node: proxmox3
    hostname: my-test-hostname
    net0: name=eth0,bridge=vmbr0,firewall=0,gw=192.168.101.1,ip=192.168.101.21/24,tag=101,type=veth
    rootfs: local-lvm:2
    memory: 1024
    swap: 0
    timezone: host
    cores: 2
    onboot: 1
    unprivileged: 1
```

Please be as specific as possible and give set-up details.

- [ X ] on-prem machine / Proxmox 8.2.7
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ X ] classic packaging / salt.deb + pip install saltext.proxmox
- [ X ] onedir packaging / --versions-report shows "Salt Package Information: Package Type: onedir"
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
salt-cloud --no-deploy --profile my-first-cloud-profile my-test-hostname
[ERROR   ] There was a profile error: name '__opts__' is not defined

**Expected behavior**
Successful creation of the LXC

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
            Salt: 3007.1

Python Version:
          Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
 Apache Libcloud: Not Installed
            cffi: 1.16.0
        cherrypy: 18.8.0
        dateutil: 2.8.2
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
          Jinja2: 3.1.4
         libgit2: Not Installed
    looseversion: 1.3.0
        M2Crypto: Not Installed
            Mako: Not Installed
         msgpack: 1.0.7
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       packaging: 23.1
       pycparser: 2.21
        pycrypto: Not Installed
    pycryptodome: 3.19.1
          pygit2: Not Installed
    python-gnupg: 0.5.2
          PyYAML: 6.0.1
           PyZMQ: 25.1.2
          relenv: 0.16.0
           smmap: Not Installed
         timelib: 0.3.0
         Tornado: 6.3.3
             ZMQ: 4.3.4

Salt Extensions:
 saltext.proxmox: 2.0.0

Salt Package Information:
    Package Type: onedir

System Versions:
            dist: debian 12.7 bookworm
          locale: utf-8
         machine: x86_64
         release: 6.8.12-1-pve
          system: Linux
         version: Debian GNU/Linux 12.7 bookworm
```
</details>

**Additional context**

I am able to get salt-cloud to execute normally when I remove the whole block from "filter_event" function with the "__opts__" references, lines 2030 to 2036:

https://github.com/saltstack/salt/blob/2b266935e42780ebd86b3a144d6897f0ae174b2b/salt/utils/cloud.py#L2031
